#!/usr/bin/env bash
#Redirect one web url to another
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
REDIRECT_301="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$REDIRECT_301/" /etc/nginx/sites-available/default
service nginx start
