#!/usr/bin/env bash
#Web Stack Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
