#!/usr/bin/env bash
#Web Stack Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
