#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user.

# Make user 'nginx' in nginx config file
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# netstat: apache is using port 8080
pkill apache2
sudo -u nginx service nginx restart
