#!/usr/bin/env bash
# Sets nginx user to nginx with appropriate permissions and nginx should
# listen on port 8080

sudo bash

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default

#exit from root
exit

sudo -u nginx service nginx restart


